Task 9. Asserts for Groups and Contacts
helga711/java_training_swt pull request #4
Opened 2022-10-24 10:00 UTC by helga711

2022-10-24 11:27 UTC, AntonBosov requested changes
если списки не сравниваются в тестах по созданию, удалению и модификации, это некорректно выполненное задание и нужно исправить, чтобы сравнение проходило

2022-10-24 11:35 UTC, helga711 commented
> если списки не сравниваются в тестах по созданию, удалению и модификации, это некорректно выполненное задание и нужно исправить, чтобы сравнение проходило

Assert.assertEquals(after, before) есть во всех тестах. Что имеешь в виду под "если не сравниваются"?

2022-10-24 11:39 UTC, AntonBosov requested changes
добавил коммнт к конкретной строчке

2022-10-24 11:39 UTC, AntonBosov commented on addressbook-web-tests/src/test/java/ru/stqa/pft/addressbook/tests/ContactCreationTests.java
> +    Assert.assertEquals(after, before, "Contacts' list is invalid after creation of the contact.");
вот это сообщение некорректное и тест не проходит, фейлится. Плюс у контакто нужно сравнение делать не по id, а по другим полям, чтобы определить уникальность.

2022-10-24 11:42 UTC, helga711 commented on addressbook-web-tests/src/test/java/ru/stqa/pft/addressbook/tests/ContactCreationTests.java
> +    Assert.assertEquals(after, before, "Contacts' list is invalid after creation of the contact.");
это не сравнение, это сортировка по id. сравнение выполняется по методу equals:
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        ContactData that = (ContactData) o;
        return Objects.equals(firstName, that.firstName) && Objects.equals(lastName, that.lastName);
    }

2022-10-24 11:47 UTC, helga711 commented on addressbook-web-tests/src/test/java/ru/stqa/pft/addressbook/tests/ContactCreationTests.java
> +    Assert.assertEquals(after, before, "Contacts' list is invalid after creation of the contact.");
вот так, например, будет выглядеть ошибка, если в before положить неправильный контакт (не тот, что создали):
    ContactData contactData1 = new ContactData("Test 2", "Test 2", "Test 3", "+79655555555", "test@test.com");
    before.add(contactData1);
![image](https://user-images.githubusercontent.com/114514838/197518456-49f83164-72d9-4d31-9e42-c2f0118ef11e.png)

2022-11-04 15:28 UTC, merged

2022-11-11 19:00 UTC, helga711 commented on addressbook-web-tests/src/test/java/ru/stqa/pft/addressbook/tests/ContactModificationTests.java
>      ContactData contactData = new ContactData("Edit 1", "Edit 2", "Edit 3", "+79666666666", "edit@test.com");
Нужно добавить before.get(before.size() - 1).getId()

2022-12-12 12:38 UTC, Kr1sPo commented on addressbook-web-tests/src/test/java/ru/stqa/pft/addressbook/model/ContactData.java
> +    public void setId(int id) {
Думаю и тут, и в GroupData можно удалить setId. Они вроде больше в коде не используются.